import type { Build, Character, Weapon, Mod, MeleeWeaponType, RangedWeaponType } from './types';
import { PlaceHolderImages } from './placeholder-images';
import { getModImage } from './mod-images';

const getImage = (id: string) => PlaceHolderImages.find(img => img.id === id)?.imageUrl ?? `https://picsum.photos/seed/${id}/400/400`;

const generateId = (name: string) => name.toLowerCase().replace(/\s+/g, '-').replace(/'/g, '');

export const allCharacters: Character[] = [
  { name: 'Berenica', element: 'Umbro', role: 'DPS (Weapon DMG)', melee: 'Sword', ranged: 'Dual Pistols' },
  { name: 'Daphne', element: 'Anemo', role: 'Support (CC, Healing)', melee: 'Whipsword', ranged: 'Assault Rifle' },
  { name: 'Fina', element: 'Hydro', role: 'Support', melee: 'Whipsword', ranged: 'Pistol' },
  { name: 'Fushu', element: 'Umbro', role: 'DPS (Weapon DMG)', melee: 'Katana', ranged: 'Pistol' },
  { name: 'Hellfire', element: 'Pyro', role: 'DPS (Skill DMG)', melee: 'Greatsword', ranged: 'Grenade Launcher' },
  { name: 'Hilda', element: 'Electro', role: 'DPS (Skill Damage)', melee: 'Whipsword', ranged: 'Assault Rifle' },
  { name: 'Kezhou', element: 'Pyro', role: 'DPS (Weapon DMG)', melee: 'Greatsword', ranged: 'Grenade Launcher' },
  { name: 'Lady Nifle', element: 'Lumino', role: 'DPS (Skill Damage)', melee: 'Katana', ranged: 'Pistol' },
  { name: 'Lisbell', element: 'Lumino', role: 'DPS (Weapon DMG)', melee: 'Greatsword', ranged: 'Shotgun' },
  { name: 'Lynn', element: 'Pyro', role: 'DPS (Weapon DMG)', melee: 'Greatsword', ranged: 'Dual Pistols' },
  { name: 'Margie', element: 'Pyro', role: 'DPS (Skill DMG, CC)', melee: 'Polearm', ranged: 'Shotgun' },
  { name: 'Outsider', element: 'Anemo', role: 'DPS (Weapon DMG)', melee: 'Dual Blades', ranged: 'Dual Pistols' },
  { name: 'Phantasio', element: 'Umbro', role: 'DPS (Skill DMG)', melee: 'Greatsword', ranged: 'Shotgun' },
  { name: 'Player', element: 'Lumino', role: 'DPS (Weapon/Skill DMG)', melee: 'Sword', ranged: 'Assault Rifle' },
  { name: 'Psyche', element: 'Anemo', role: 'DPS (Weapon/Skill DMG)', melee: 'Polearm', ranged: 'Assault Rifle' },
  { name: 'Randy', element: 'Electro', role: 'Support (Shielding)', melee: 'Sword', ranged: 'Pistol' },
  { name: 'Rebecca', element: 'Hydro', role: 'DPS (Skill DMG, Summon)', melee: 'Polearm', ranged: 'Grenade Launcher' },
  { name: 'Rhythm', element: 'Electro', role: 'DPS (Skill Damage)', melee: 'Katana', ranged: 'Assault Rifle' },
  { name: 'Sibylle', element: 'Electro', role: 'DPS (Skill Damage)', melee: 'Whipsword', ranged: 'Pistol' },
  { name: 'Tabethe', element: 'Hydro', role: 'Support (Summon, CC)', melee: 'Sword', ranged: 'Bow' },
  { name: 'Truffle and Filbert', element: 'Anemo', role: 'Support (Healing)', melee: 'Polearm', ranged: 'Bow' },
  { name: 'Yale and Oliver', element: 'Pyro', role: 'DPS (Skill DMG)', melee: 'Sword', ranged: 'Shotgun' },
  { name: 'Yuming', element: 'Anemo', role: 'Support', melee: 'Polearm', ranged: 'Bow' },
  { name: 'Zhiliu', element: 'Pyro', role: 'DPS (Skill DMG)', melee: 'Sword', ranged: 'Shotgun' }
].map(c => ({ ...c, id: generateId(c.name), image: getImage(`character-${generateId(c.name)}`) } as Character)).sort((a, b) => a.name.localeCompare(b.name));

export const allMeleeWeapons: Weapon[] = [
  { name: 'Aureate Yore', type: 'Dual Blades', attackType: 'Smash', maxAttack: 225.94 },
  { name: 'Blade Amberglow', type: 'Sword', attackType: 'Smash', maxAttack: 238.49 },
  { name: 'Elpides Abound', type: 'Polearm', attackType: 'Slash', maxAttack: 276.15 },
  { name: 'Exiled Fangs', type: 'Dual Blades', attackType: 'Slash', maxAttack: 263.6 },
  { name: 'Fathomless Sharkgaze', type: 'Dual Blades', attackType: 'Spike', maxAttack: 251.04 },
  { name: 'Ingenious Tactics', type: 'Sword', attackType: 'Slash', maxAttack: 225.94 },
  { name: 'Ironforger', type: 'Greatsword', attackType: 'Slash', maxAttack: 225.94 },
  { name: 'Momiji Itteki', type: 'Katana', attackType: 'Slash', maxAttack: 239.49 },
  { name: 'Punitive Inferno', type: 'Greatsword', attackType: 'Smash', maxAttack: 238.49 },
  { name: 'Pyrothirst', type: 'Greatsword', attackType: 'Smash', maxAttack: 213.39 },
  { name: 'Remanent Reminiscence', type: 'Sword', attackType: 'Spike', maxAttack: 213.39 },
  { name: 'Sacred Favour', type: 'Katana', attackType: 'Spike', maxAttack: 251.04 },
  { name: 'Shackle of Lonewolf', type: 'Sword', attackType: 'Spike', maxAttack: 251.04 },
  { name: "Siren's Kiss", type: 'Polearm', attackType: 'Spike', maxAttack: 263.6 },
  { name: 'Tetherlash', type: 'Whipsword', attackType: 'Smash', maxAttack: 238.49 },
  { name: 'Undying Oneiros', type: 'Whipsword', attackType: 'Spike', maxAttack: 263.6 },
  { name: 'Vernal Jade Halberd', type: 'Polearm', attackType: 'Spike', maxAttack: 225.94 },
  { name: 'Viridis Reefs', type: 'Whipsword', attackType: 'Spike', maxAttack: 213.39 },
  { name: 'Wandering Rose', type: 'Sword', attackType: 'Spike', maxAttack: 251.04 },
  { name: 'Wanewraith', type: 'Polearm', attackType: 'Slash', maxAttack: 238.49 },
  { name: 'Withershade', type: 'Katana', attackType: 'Smash', maxAttack: 213.39 }
].map(w => ({ ...w, id: generateId(w.name), image: getImage(`weapon-${generateId(w.name)}`) } as Weapon)).sort((a, b) => a.name.localeCompare(b.name));

export const allRangedWeapons: Weapon[] = [
  { name: 'Arclight Apocalypses', type: 'Bow', attackType: 'Smash', maxAttack: 225.94 },
  { name: 'Blast Artistry', type: 'Shotgun', attackType: 'Smash', maxAttack: 188.28 },
  { name: 'Bluecurrent Pulse', type: 'Dual Pistols', attackType: 'Spike', maxAttack: 238.49 },
  { name: 'Day of Sacred Verdict', type: 'Shotgun', attackType: 'Slash', maxAttack: 213.99 },
  { name: 'Daybreak Hymn', type: 'Assault Rifle', attackType: 'Spike', maxAttack: 225.94 },
  { name: 'Destructo', type: 'Grenade Launcher', attackType: 'Smash', maxAttack: 225.94 },
  { name: "Dreamweaver's Feather", type: 'Assault Rifle', attackType: 'Slash', maxAttack: 188.28 },
  { name: 'Embla Inflorescence', type: 'Bow', attackType: 'Slash', maxAttack: 188.28 },
  { name: 'Entropic Singularity', type: 'Pistol', attackType: 'Slash', maxAttack: 200.84 },
  { name: 'Excresduo', type: 'Dual Pistols', attackType: 'Spike', maxAttack: 263.6 },
  { name: 'Exiled Thunderwyrm', type: 'Assault Rifle', attackType: 'Spike', maxAttack: 188.28 },
  { name: 'Flamme De Epuration', type: 'Assault Rifle', attackType: 'Slash', maxAttack: 238.49 },
  { name: 'Guixu Ratchet', type: 'Grenade Launcher', attackType: 'Slash', maxAttack: 200.84 },
  { name: 'Osteobreaker', type: 'Assault Rifle', attackType: 'Spike', maxAttack: 213.39 },
  { name: 'Rendhusk', type: 'Pistol', attackType: 'Smash', maxAttack: 188.28 },
  { name: 'Sacrosanct Chorus', type: 'Dual Pistols', attackType: 'Slash', maxAttack: 225.94 },
  { name: 'Sacrosant Decrcee', type: 'Pistol', attackType: 'Spike', maxAttack: 225.94 },
  { name: 'Screamshot', type: 'Shotgun', attackType: 'Spike', maxAttack: 225.94 },
  { name: 'Searing Sandwhisper', type: 'Bow', attackType: 'Spike', maxAttack: 213.39 },
  { name: 'Silent Sower', type: 'Shotgun', attackType: 'Smash', maxAttack: 200.84 },
  { name: 'Silverwhite Edict', type: 'Grenade Launcher', attackType: 'Spike', maxAttack: 238.49 },
  { name: 'Soulrend', type: 'Bow', attackType: 'Smash', maxAttack: 238.49 },
  { name: 'Stellar Finality', type: 'Grenade Launcher', attackType: 'Smash', maxAttack: 175.73 },
  { name: 'Submerged Serenade', type: 'Assault Rifle', attackType: 'Slash', maxAttack: 200.84 }
].map(w => ({ ...w, id: generateId(w.name), image: getImage(`weapon-${generateId(w.name)}`) } as Weapon)).sort((a, b) => a.name.localeCompare(b.name));

export const allWeapons: Weapon[] = [...allMeleeWeapons, ...allRangedWeapons].sort((a, b) => a.name.localeCompare(b.name));
export const allWeaponTypes = [...new Set(allWeapons.map(w => w.type))].sort();


export const allMods: Mod[] = [
  {
    "name": "Arbiter's Illusionary Sacrifice",
    "rarity": 4,
    "modType": "Characters",
    "element": "Umbro",
    "symbol": "⊙",
    "mainAttribute": "Skill DMG +30%",
    "effect": "When an Umbro character consumes Sanity, they gain 1 stack that increases Weapon CRIT Chance by 5.4% for 15s, up to 15 stacks.",
    "tolerance": 24,
    "track": 5,
    "source": "Level 65"
  },
  {
    "name": "Arbiter's Illusionary Sacrifice",
    "rarity": 5,
    "modType": "Characters",
    "element": "Umbro",
    "symbol": "⊙",
    "mainAttribute": "Skill DMG +30%",
    "effect": "When an Umbro character consumes Sanity, they gain 1 stack that increases Weapon CRIT Chance by 5.4% for 15s, up to 15 stacks.",
    "tolerance": 22,
    "track": 5,
    "source": "Forge"
  },
  {
    "name": "Bahamut's Frosty Torrent",
    "rarity": 4,
    "modType": "Characters",
    "element": "Hydro",
    "symbol": "⊙",
    "mainAttribute": "Skill DMG +30%",
    "effect": "When a Hydro character use a skill, the user and nearby allies gain an ATK increases equal to 11.4% of the user's ATK (up to 275) for 10s.",
    "tolerance": 24,
    "track": 5,
    "source": "Level 65"
  },
  {
    "name": "Bahamut's Frosty Torrent",
    "rarity": 5,
    "modType": "Characters",
    "element": "Hydro",
    "symbol": "⊙",
    "mainAttribute": "Skill DMG +30%",
    "effect": "When a Hydro character use a skill, the user and nearby allies gain an ATK increases equal to 11.4% of the user's ATK (up to 275) for 10s.",
    "tolerance": 22,
    "track": 5,
    "source": "Forge"
  },
  {
    "name": "Bahamut's Misty Veil",
    "rarity": 4,
    "modType": "Characters",
    "element": "Hydro",
    "symbol": "⊙",
    "mainAttribute": "Skill DMG +30%",
    "effect": "Hydro Charactes' Summon gains an ATK speed boost equal to 27% of the summoner's melee weapon ATK Speed and a Skill range boost equal to Summoner's Skill range.",
    "tolerance": 24,
    "track": 5,
    "source": "Level 65"
  },
  {
    "name": "Bahamut's Misty Veil",
    "rarity": 5,
    "modType": "Characters",
    "element": "Hydro",
    "symbol": "⊙",
    "mainAttribute": "Skill DMG +30%",
    "effect": "Hydro Charactes' Summon gains an ATK speed boost equal to 27% of the summoner's melee weapon ATK Speed and a Skill range boost equal to Summoner's Skill range.",
    "tolerance": 22,
    "track": 5,
    "source": "Forge"
  },
  {
    "name": "Cerberus's Celerity",
    "rarity": 3,
    "modType": "Melee Weapon",
    "mainAttribute": "ATK Speed +20%",
    "tolerance": 12,
    "track": 5,
    "source": "Level 30"
  },
  {
    "name": "Cerberus's Celerity",
    "rarity": 5,
    "modType": "Melee Weapon",
    "symbol": "⊙",
    "mainAttribute": "ATK Speed +42%",
    "tolerance": 20,
    "track": 5,
    "source": "Forge"
  },
  {
    "name": "Cerberus's Crusher Trammel",
    "rarity": 2,
    "modType": "Melee Weapon",
    "mainAttribute": "Smash ATK +20%\nTrigger Probability +40%",
    "tolerance": 9,
    "track": 3,
    "source": "Level 20"
  },
  {
    "name": "Cerberus's Crusher",
    "rarity": 3,
    "modType": "Melee Weapon",
    "mainAttribute": "Smash ATK +50%",
    "tolerance": 12,
    "track": 5,
    "source": "Level 30"
  },
  {
    "name": "Cerberus's Crusher",
    "rarity": 5,
    "modType": "Melee Weapon",
    "symbol": "◬",
    "mainAttribute": "Smash ATK +54%",
    "tolerance": 9,
    "track": 5,
    "source": "Forge"
  },
  {
    "name": "Cerberus's Edge Trammel",
    "rarity": 2,
    "modType": "Melee Weapon",
    "mainAttribute": "Slash ATK +20%\nTrigger Probability +40%",
    "tolerance": 9,
    "track": 3,
    "source": "Level 20"
  },
  {
    "name": "Cerberus's Edge",
    "rarity": 3,
    "modType": "Melee Weapon",
    "mainAttribute": "Slash ATK +50%",
    "tolerance": 12,
    "track": 5,
    "source": "Level 30"
  },
  {
    "name": "Cerberus's Edge",
    "rarity": 5,
    "modType": "Melee Weapon",
    "symbol": "◬",
    "mainAttribute": "Slash ATK +54%",
    "tolerance": 9,
    "track": 5,
    "source": "Forge"
  },
  {
    "name": "Cerberus's Focus",
    "rarity": 4,
    "modType": "Melee Weapon",
    "symbol": "◬",
    "mainAttribute": "CRIT Chance +100%",
    "tolerance": 17,
    "track": 5,
    "source": "Level 40"
  },
  {
    "name": "Cerberus's Impetus Focus",
    "rarity": 2,
    "modType": "Melee Weapon",
    "mainAttribute": "ATK +30%\nCrit Chance +40%",
    "tolerance": 11,
    "track": 3,
    "source": "Level 20"
  },
  {
    "name": "Cerberus's Impetus",
    "rarity": 4,
    "modType": "Melee Weapon",
    "symbol": "◬",
    "mainAttribute": "ATK +75%",
    "tolerance": 10,
    "track": 5,
    "source": "Level 40"
  },
  {
    "name": "Cerberus's Impetus",
    "rarity": 5,
    "modType": "Melee Weapon",
    "symbol": "◬",
    "mainAttribute": "ATK +82%",
    "tolerance": 10,
    "track": 5,
    "source": "Forge"
  },
  {
    "name": "Cerberus's Impetus Focus",
    "rarity": 5,
    "modType": "Melee Weapon",
    "symbol": "◬",
    "mainAttribute": "ATK +41%\nCRIT Chance +54%",
    "tolerance": 12,
    "track": 5,
    "source": "Forge"
  },
  {
    "name": "Cerberus's Penetration Trammel",
    "rarity": 2,
    "modType": "Melee Weapon",
    "mainAttribute": "Spike ATK +20%\nTrigger Probability +40%",
    "tolerance": 9,
    "track": 3,
    "source": "Level 20"
  },
  {
    "name": "Cerberus's Penetration",
    "rarity": 3,
    "modType": "Melee Weapon",
    "mainAttribute": "Spike ATK +50%",
    "tolerance": 12,
    "track": 5,
    "source": "Level 30"
  },
  {
    "name": "Cerberus's Penetration",
    "rarity": 5,
    "modType": "Melee Weapon",
    "symbol": "◬",
    "mainAttribute": "Spike ATK +54%",
    "tolerance": 9,
    "track": 5,
    "source": "Forge"
  },
  {
    "name": "Cerberus's Rage Trammel",
    "rarity": 2,
    "modType": "Melee Weapon",
    "mainAttribute": "Crit Damage +40%\nTrigger Probability +40%",
    "tolerance": 10,
    "track": 3,
    "source": "Level 20"
  },
  {
    "name": "Cerberus's Rage",
    "rarity": 4,
    "modType": "Melee Weapon",
    "symbol": "◬",
    "mainAttribute": "CRIT Damage +100%",
    "tolerance": 14,
    "track": 5,
    "source": "Level 40"
  },
  {
    "name": "Cerberus's Rage Trammel",
    "rarity": 5,
    "modType": "Melee Weapon",
    "symbol": "☽",
    "mainAttribute": "CRIT Damage +54%\nTrigger Probability +54%",
    "tolerance": 11,
    "track": 5,
    "source": "Forge"
  },
  {
    "name": "Cerberus's Threshold",
    "rarity": 5,
    "modType": "Melee Weapon",
    "symbol": "⊙",
    "mainAttribute": "ATK Range +1.36",
    "tolerance": 10,
    "track": 5,
    "source": "Forge"
  },
  {
    "name": "Cerberus's Trammel",
    "rarity": 4,
    "modType": "Melee Weapon",
    "symbol": "☽",
    "mainAttribute": "Trigger Probability +100%",
    "tolerance": 12,
    "track": 5,
    "source": "Level 40"
  },
  {
    "name": "Cerberus's Treshold",
    "rarity": 3,
    "modType": "Melee Weapon",
    "mainAttribute": "ATK Range +1",
    "tolerance": 9,
    "track": 5,
    "source": "Level 30"
  },
  {
    "name": "Covenanter's Blaze Resolve",
    "rarity": 4,
    "modType": "Characters",
    "element": "Lumino",
    "symbol": "☽",
    "mainAttribute": "ATK +48%\nResolve +4%",
    "effect": "Once upgraded to +5, this Demon Wedge can be equipped in multiples",
    "tolerance": 15,
    "track": 5,
    "source": "Level 65"
  },
  {
    "name": "Covenanter's Blaze Eternity",
    "rarity": 4,
    "modType": "Characters",
    "element": "Lumino",
    "symbol": "◊",
    "mainAttribute": "ATK +48%\nSkill Duration +18%",
    "effect": "Once upgraded to +5, this Demon Wedge can be equipped in multiples",
    "tolerance": 18,
    "track": 5,
    "source": "Level 65"
  },
  {
    "name": "Covenanter's Blaze Standfast",
    "rarity": 4,
    "modType": "Characters",
    "element": "Anemo",
    "symbol": "◬",
    "mainAttribute": "ATK +48%\nDEF +48%",
    "effect": "Once upgraded to +5, this Demon Wedge can be equipped in multiples",
    "tolerance": 16,
    "track": 5,
    "source": "Level 65"
  },
  {
    "name": "Covenanter's Blaze Resolve",
    "rarity": 4,
    "modType": "Characters",
    "element": "Anemo",
    "symbol": "☽",
    "mainAttribute": "ATK +48%\nResolve +4%",
    "effect": "Once upgraded to +5, this Demon Wedge can be equipped in multiples",
    "tolerance": 15,
    "track": 5,
    "source": "Level 65"
  },
  {
    "name": "Covenanter's Blaze Volition",
    "rarity": 4,
    "modType": "Characters",
    "element": "Anemo",
    "symbol": "◊",
    "mainAttribute": "ATK +48%\nSkill DMG +24%",
    "effect": "Once upgraded to +5, this Demon Wedge can be equipped in multiples",
    "tolerance": 18,
    "track": 5,
    "source": "Level 65"
  },
  {
    "name": "Covenanter's Blaze Nirvana",
    "rarity": 4,
    "modType": "Characters",
    "element": "Electro",
    "symbol": "◬",
    "mainAttribute": "ATK +48%\nHP +48%",
    "effect": "Once upgraded to +5, this Demon Wedge can be equipped in multiples",
    "tolerance": 16,
    "track": 5,
    "source": "Level 65"
  },
  {
    "name": "Covenanter's Blaze Morale",
    "rarity": 4,
    "modType": "Characters",
    "element": "Electro",
    "symbol": "☽",
    "mainAttribute": "ATK +48%\nMorale +12%",
    "effect": "Once upgraded to +5, this Demon Wedge can be equipped in multiples",
    "tolerance": 15,
    "track": 5,
    "source": "Level 65"
  },
  {
    "name": "Covenanter's Blaze Volition",
    "rarity": 4,
    "modType": "Characters",
    "element": "Electro",
    "symbol": "◊",
    "mainAttribute": "ATK +48%\nSkill DMG +24%",
    "effect": "Once upgraded to +5, this Demon Wedge can be equipped in multiples",
    "tolerance": 18,
    "track": 5,
    "source": "Level 65"
  },
  {
    "name": "Covenanter's Blaze Standfast",
    "rarity": 4,
    "modType": "Characters",
    "element": "Pyro",
    "symbol": "◬",
    "mainAttribute": "ATK +48%\nDEF +48%",
    "effect": "Once upgraded to +5, this Demon Wedge can be equipped in multiples",
    "tolerance": 16,
    "track": 5,
    "source": "Level 65"
  },
  {
    "name": "Covenanter's Blaze Eternity",
    "rarity": 4,
    "modType": "Characters",
    "element": "Pyro",
    "symbol": "☽",
    "mainAttribute": "ATK +48%\nSkill Duration +18%",
    "effect": "Once upgraded to +5, this Demon Wedge can be equipped in multiples",
    "tolerance": 18,
    "track": 5,
    "source": "Level 65"
  },
  {
    "name": "Covenanter's Blaze Inspo",
    "rarity": 4,
    "modType": "Characters",
    "element": "Pyro",
    "symbol": "◊",
    "mainAttribute": "ATK +48%\nSkill Efficiency +12%",
    "effect": "Once upgraded to +5, this Demon Wedge can be equipped in multiples",
    "tolerance": 16,
    "track": 5,
    "source": "Level 65"
  },
  {
    "name": "Covenanter's Blaze Nirvana",
    "rarity": 4,
    "modType": "Characters",
    "element": "Hydro",
    "symbol": "◬",
    "mainAttribute": "ATK +48%\nHP +48%",
    "effect": "Once upgraded to +5, this Demon Wedge can be equipped in multiples",
    "tolerance": 16,
    "track": 5,
    "source": "Level 65"
  },
  {
    "name": "Covenanter's Blaze Spectrum",
    "rarity": 4,
    "modType": "Characters",
    "element": "Hydro",
    "symbol": "☽",
    "mainAttribute": "ATK +48%\nSkill Range +30%",
    "effect": "Once upgraded to +5, this Demon Wedge can be equipped in multiples",
    "tolerance": 17,
    "track": 5,
    "source": "Level 65"
  },
  {
    "name": "Covenanter's Blaze Inspo",
    "rarity": 4,
    "modType": "Characters",
    "element": "Hydro",
    "symbol": "◊",
    "mainAttribute": "ATK +48%\nSkill Efficiency +12%",
    "effect": "Once upgraded to +5, this Demon Wedge can be equipped in multiples",
    "tolerance": 16,
    "track": 5,
    "source": "Level 65"
  },
  {
    "name": "Covenanter's Blaze Morale",
    "rarity": 4,
    "modType": "Characters",
    "element": "Umbro",
    "symbol": "☽",
    "mainAttribute": "ATK +48%\nMorale +12%",
    "effect": "Once upgraded to +5, this Demon Wedge can be equipped in multiples",
    "tolerance": 15,
    "track": 5,
    "source": "Level 65"
  },
  {
    "name": "Covenanter's Blaze Spectrum",
    "rarity": 4,
    "modType": "Characters",
    "element": "Umbro",
    "symbol": "◊",
    "mainAttribute": "ATK +48%\nSkill Range +30%",
    "effect": "Once upgraded to +5, this Demon Wedge can be equipped in multiples",
    "tolerance": 17,
    "track": 5,
    "source": "Level 65"
  },
  {
    "name": "Covenanter's Blaze Resolve",
    "rarity": 5,
    "modType": "Characters",
    "element": "Lumino",
    "symbol": "☽",
    "mainAttribute": "ATK +48%\nResolve +4%",
    "effect": "Once upgraded to +5, this Demon Wedge can be equipped in multiples",
    "tolerance": 12,
    "track": 5,
    "source": "Forge"
  },
  {
    "name": "Covenanter's Blaze Eternity",
    "rarity": 5,
    "modType": "Characters",
    "element": "Lumino",
    "symbol": "◊",
    "mainAttribute": "ATK +48%\nSkill Duration +18%",
    "effect": "Once upgraded to +5, this Demon Wedge can be equipped in multiples",
    "tolerance": 15,
    "track": 5,
    "source": "Forge"
  },
  {
    "name": "Covenanter's Blaze Standfast",
    "rarity": 5,
    "modType": "Characters",
    "element": "Anemo",
    "symbol": "◬",
    "mainAttribute": "ATK +48%\nDEF +48%",
    "effect": "Once upgraded to +5, this Demon Wedge can be equipped in multiples",
    "tolerance": 13,
    "track": 5,
    "source": "Forge"
  },
  {
    "name": "Covenanter's Blaze Resolve",
    "rarity": 5,
    "modType": "Characters",
    "element": "Anemo",
    "symbol": "☽",
    "mainAttribute": "ATK +48%\nResolve +4%",
    "effect": "Once upgraded to +5, this Demon Wedge can be equipped in multiples",
    "tolerance": 12,
    "track": 5,
    "source": "Forge"
  },
  {
    "name": "Covenanter's Blaze Volition",
    "rarity": 5,
    "modType": "Characters",
    "element": "Anemo",
    "symbol": "◊",
    "mainAttribute": "ATK +48%\nSkill DMG +24%",
    "effect": "Once upgraded to +5, this Demon Wedge can be equipped in multiples",
    "tolerance": 15,
    "track": 5,
    "source": "Forge"
  },
  {
    "name": "Covenanter's Blaze Nirvana",
    "rarity": 5,
    "modType": "Characters",
    "element": "Electro",
    "symbol": "◬",
    "mainAttribute": "ATK +48%\nHP +48%",
    "effect": "Once upgraded to +5, this Demon Wedge can be equipped in multiples",
    "tolerance": 13,
    "track": 5,
    "source": "Forge"
  },
  {
    "name": "Covenanter's Blaze Morale",
    "rarity": 5,
    "modType": "Characters",
    "element": "Electro",
    "symbol": "☽",
    "mainAttribute": "ATK +48%\nMorale +12%",
    "effect": "Once upgraded to +5, this Demon Wedge can be equipped in multiples",
    "tolerance": 12,
    "track": 5,
    "source": "Forge"
  },
  {
    "name": "Covenanter's Blaze Volition",
    "rarity": 5,
    "modType": "Characters",
    "element": "Electro",
    "symbol": "◊",
    "mainAttribute": "ATK +48%\nSkill DMG +24%",
    "effect": "Once upgraded to +5, this Demon Wedge can be equipped in multiples",
    "tolerance": 15,
    "track": 5,
    "source": "Forge"
  },
  {
    "name": "Covenanter's Blaze Standfast",
    "rarity": 5,
    "modType": "Characters",
    "element": "Pyro",
    "symbol": "◬",
    "mainAttribute": "ATK +48%\nDEF +48%",
    "effect": "Once upgraded to +5, this Demon Wedge can be equipped in multiples",
    "tolerance": 13,
    "track": 5,
    "source": "Forge"
  },
  {
    "name": "Covenanter's Blaze Eternity",
    "rarity": 5,
    "modType": "Characters",
    "element": "Pyro",
    "symbol": "☽",
    "mainAttribute": "ATK +48%\nSkill Duration +18%",
    "effect": "Once upgraded to +5, this Demon Wedge can be equipped in multiples",
    "tolerance": 15,
    "track": 5,
    "source": "Forge"
  },
  {
    "name": "Covenanter's Blaze Inspo",
    "rarity": 5,
    "modType": "Characters",
    "element": "Pyro",
    "symbol": "◊",
    "mainAttribute": "ATK +48%\nSkill Efficiency +12%",
    "effect": "Once upgraded to +5, this Demon Wedge can be equipped in multiples",
    "tolerance": 13,
    "track": 5,
    "source": "Forge"
  },
  {
    "name": "Covenanter's Blaze Nirvana",
    "rarity": 5,
    "modType": "Characters",
    "element": "Hydro",
    "symbol": "◬",
    "mainAttribute": "ATK +48%\nHP +48%",
    "effect": "Once upgraded to +5, this Demon Wedge can be equipped in multiples",
    "tolerance": 13,
    "track": 5,
    "source": "Forge"
  },
  {
    "name": "Covenanter's Blaze Spectrum",
    "rarity": 5,
    "modType": "Characters",
    "element": "Hydro",
    "symbol": "☽",
    "mainAttribute": "ATK +48%\nSkill Range +30%",
    "effect": "Once upgraded to +5, this Demon Wedge can be equipped in multiples",
    "tolerance": 13,
    "track": 5,
    "source": "Forge"
  },
  {
    "name": "Covenanter's Blaze Inspo",
    "rarity": 5,
    "modType": "Characters",
    "element": "Hydro",
    "symbol": "◊",
    "mainAttribute": "ATK +48%\nSkill Efficiency +12%",
    "effect": "Once upgraded to +5, this Demon Wedge can be equipped in multiples",
    "tolerance": 13,
    "track": 5,
    "source": "Forge"
  },
  {
    "name": "Covenanter's Blaze Morale",
    "rarity": 5,
    "modType": "Characters",
    "element": "Umbro",
    "symbol": "☽",
    "mainAttribute": "ATK +48%\nMorale +12%",
    "effect": "Once upgraded to +5, this Demon Wedge can be equipped in multiples",
    "tolerance": 12,
    "track": 5,
    "source": "Forge"
  },
  {
    "name": "Covenanter's Blaze Spectrum",
    "rarity": 5,
    "modType": "Characters",
    "element": "Umbro",
    "symbol": "◊",
    "mainAttribute": "ATK +48%\nSkill Range +30%",
    "effect": "Once upgraded to +5, this Demon Wedge can be equipped in multiples",
    "tolerance": 13,
    "track": 5,
    "source": "Forge"
  },
  {
    "name": "Covenanter's Nirvana Volition",
    "rarity": 4,
    "modType": "Characters",
    "element": "Lumino",
    "symbol": "⊙",
    "mainAttribute": "HP +48%\nSkill DMG +24%",
    "effect": "Once upgraded to +5, this Demon Wedge can be equipped in multiples",
    "tolerance": 18,
    "track": 5,
    "source": "Level 65"
  },
  {
    "name": "Covenanter's Nirvana Spectrum",
    "rarity": 4,
    "modType": "Characters",
    "element": "Pyro",
    "symbol": "⊙",
    "mainAttribute": "HP +48%\nSkill Range +30%",
    "effect": "Once upgraded to +5, this Demon Wedge can be equipped in multiples",
    "tolerance": 17,
    "track": 5,
    "source": "Level 65"
  },
  {
    "name": "Covenanter's Nirvana Volition",
    "rarity": 5,
    "modType": "Characters",
    "element": "Lumino",
    "symbol": "⊙",
    "mainAttribute": "HP +48%\nSkill DMG +24%",
    "effect": "Once upgraded to +5, this Demon Wedge can be equipped in multiples",
    "tolerance": 15,
    "track": 5,
    "source": "Forge"
  },
  {
    "name": "Covenanter's Nirvana Spectrum",
    "rarity": 5,
    "modType": "Characters",
    "element": "Pyro",
    "symbol": "⊙",
    "mainAttribute": "HP +48%\nSkill Range +30%",
    "effect": "Once upgraded to +5, this Demon Wedge can be equipped in multiples",
    "tolerance": 13,
    "track": 5,
    "source": "Forge"
  },
  {
    "name": "Covenanter's Scorch",
    "rarity": 4,
    "modType": "Characters",
    "element": "Lumino",
    "symbol": "◬",
    "mainAttribute": "ATK +96%",
    "effect": "Once upgraded to +5, this Demon Wedge can be equipped in multiples",
    "tolerance": 16,
    "track": 5,
    "source": "Level 65"
  },
  {
    "name": "Covenanter's Scorch",
    "rarity": 4,
    "modType": "Characters",
    "element": "Umbro",
    "symbol": "◬",
    "mainAttribute": "ATK +96%",
    "effect": "Once upgraded to +5, this Demon Wedge can be equipped in multiples",
    "tolerance": 16,
    "track": 5,
    "source": "Level 65"
  },
  {
    "name": "Covenanter's Scorch",
    "rarity": 5,
    "modType": "Characters",
    "element": "Lumino",
    "symbol": "◬",
    "mainAttribute": "ATK +96%",
    "effect": "Once upgraded to +5, this Demon Wedge can be equipped in multiples",
    "tolerance": 13,
    "track": 5,
    "source": "Forge"
  },
  {
    "name": "Covenanter's Scorch",
    "rarity": 5,
    "modType": "Characters",
    "element": "Umbro",
    "symbol": "◬",
    "mainAttribute": "ATK +96%",
    "effect": "Once upgraded to +5, this Demon Wedge can be equipped in multiples",
    "tolerance": 13,
    "track": 5,
    "source": "Forge"
  },
  {
    "name": "Covenanter's Standfast Eternity",
    "rarity": 4,
    "modType": "Characters",
    "element": "Electro",
    "symbol": "⊙",
    "mainAttribute": "DEF +48%\nSkill Duration +18%",
    "effect": "Once upgraded to +5, this Demon Wedge can be equipped in multiples",
    "tolerance": 18,
    "track": 5,
    "source": "Level 65"
  },
  {
    "name": "Covenanter's Standfast Inspo",
    "rarity": 4,
    "modType": "Characters",
    "element": "Umbro",
    "symbol": "⊙",
    "mainAttribute": "DEF +48%\nSkill Efficiency +12%",
    "effect": "Once upgraded to +5, this Demon Wedge can be equipped in multiples",
    "tolerance": 16,
    "track": 5,
    "source": "Level 65"
  },
  {
    "name": "Covenanter's Standfast Eternity",
    "rarity": 5,
    "modType": "Characters",
    "element": "Electro",
    "symbol": "⊙",
    "mainAttribute": "DEF +48%\nSkill Duration +18%",
    "effect": "Once upgraded to +5, this Demon Wedge can be equipped in multiples",
    "tolerance": 15,
    "track": 5,
    "source": "Forge"
  },
  {
    "name": "Covenanter's Standfast Inspo",
    "rarity": 5,
    "modType": "Characters",
    "element": "Umbro",
    "symbol": "⊙",
    "mainAttribute": "DEF +48%\nSkill Efficiency +12%",
    "effect": "Once upgraded to +5, this Demon Wedge can be equipped in multiples",
    "tolerance": 13,
    "track": 5,
    "source": "Forge"
  },
  {
    "name": "Covenanter's Wings Eternity",
    "rarity": 4,
    "modType": "Characters",
    "element": "Anemo",
    "symbol": "⊙",
    "mainAttribute": "Max Sanity +24%\nSkill Duration +18%",
    "effect": "Once upgraded to +5, this Demon Wedge can be equipped in multiples",
    "tolerance": 16,
    "track": 5,
    "source": "Level 65"
  },
  {
    "name": "Covenanter's Wings Volition",
    "rarity": 4,
    "modType": "Characters",
    "element": "Hydro",
    "symbol": "⊙",
    "mainAttribute": "Max Sanity +24%\nSkill DMG +24%",
    "effect": "Once upgraded to +5, this Demon Wedge can be equipped in multiples",
    "tolerance": 16,
    "track": 5,
    "source": "Level 65"
  },
  {
    "name": "Covenanter's Wings Eternity",
    "rarity": 5,
    "modType": "Characters",
    "element": "Anemo",
    "symbol": "⊙",
    "mainAttribute": "Max Sanity +24%\nSkill Duration +18%",
    "effect": "Once upgraded to +5, this Demon Wedge can be equipped in multiples",
    "tolerance": 13,
    "track": 5,
    "source": "Forge"
  },
  {
    "name": "Covenanter's Wings Volition",
    "rarity": 5,
    "modType": "Characters",
    "element": "Hydro",
    "symbol": "⊙",
    "mainAttribute": "Max Sanity +24%\nSkill DMG +24%",
    "effect": "Once upgraded to +5, this Demon Wedge can be equipped in multiples",
    "tolerance": 13,
    "track": 5,
    "source": "Forge"
  },
  {
    "name": "Eldritch Cerberus's Celerity",
    "rarity": 2,
    "modType": "Melee Consonance Weapon",
    "mainAttribute": "ATK Speed +10%",
    "tolerance": 15,
    "track": 3,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Cerberus's Celerity",
    "rarity": 3,
    "modType": "Melee Consonance Weapon",
    "mainAttribute": "ATK Speed +20%",
    "tolerance": 18,
    "track": 5,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Cerberus's Celerity",
    "rarity": 4,
    "modType": "Melee Consonance Weapon",
    "symbol": "⊙",
    "mainAttribute": "ATK Speed +25%",
    "tolerance": 21,
    "track": 5,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Cerberus's Celerity",
    "rarity": 5,
    "modType": "Melee Consonance Weapon",
    "symbol": "⊙",
    "mainAttribute": "ATK Speed +27%",
    "tolerance": 26,
    "track": 5,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Cerberus's Crusher",
    "rarity": 2,
    "modType": "Melee Consonance Weapon",
    "mainAttribute": "Smash ATK +30%",
    "tolerance": 10,
    "track": 3,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Cerberus's Crusher",
    "rarity": 3,
    "modType": "Melee Consonance Weapon",
    "mainAttribute": "Smash ATK +60%",
    "tolerance": 13,
    "track": 5,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Cerberus's Crusher",
    "rarity": 4,
    "modType": "Melee Consonance Weapon",
    "symbol": "◬",
    "mainAttribute": "Smash ATK +75%",
    "tolerance": 16,
    "track": 5,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Cerberus's Crusher",
    "rarity": 5,
    "modType": "Melee Consonance Weapon",
    "symbol": "◬",
    "mainAttribute": "Smash ATK +81.6%",
    "tolerance": 21,
    "track": 5,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Cerberus's Edge",
    "rarity": 2,
    "modType": "Melee Consonance Weapon",
    "mainAttribute": "Slash ATK +30%",
    "tolerance": 10,
    "track": 3,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Cerberus's Edge",
    "rarity": 3,
    "modType": "Melee Consonance Weapon",
    "mainAttribute": "Slash ATK +60%",
    "tolerance": 13,
    "track": 5,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Cerberus's Edge",
    "rarity": 4,
    "modType": "Melee Consonance Weapon",
    "symbol": "◬",
    "mainAttribute": "Slash ATK +75%",
    "tolerance": 16,
    "track": 5,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Cerberus's Edge",
    "rarity": 5,
    "modType": "Melee Consonance Weapon",
    "symbol": "◬",
    "mainAttribute": "Slash ATK +81.6%",
    "tolerance": 21,
    "track": 5,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Cerberus's Focus",
    "rarity": 2,
    "modType": "Melee Consonance Weapon",
    "mainAttribute": "CRIT Chance +20%",
    "tolerance": 11,
    "track": 3,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Cerberus's Focus",
    "rarity": 3,
    "modType": "Melee Consonance Weapon",
    "mainAttribute": "CRIT Chance +40%",
    "tolerance": 14,
    "track": 5,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Cerberus's Focus",
    "rarity": 4,
    "modType": "Melee Consonance Weapon",
    "symbol": "◬",
    "mainAttribute": "CRIT Chance +50%",
    "tolerance": 17,
    "track": 5,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Cerberus's Focus",
    "rarity": 5,
    "modType": "Melee Consonance Weapon",
    "symbol": "◬",
    "mainAttribute": "CRIT Chance +54%",
    "tolerance": 22,
    "track": 5,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Cerberus's Impetus",
    "rarity": 2,
    "modType": "Melee Consonance Weapon",
    "mainAttribute": "ATK +30%",
    "tolerance": 10,
    "track": 3,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Cerberus's Impetus",
    "rarity": 3,
    "modType": "Melee Consonance Weapon",
    "mainAttribute": "ATK +60%",
    "tolerance": 13,
    "track": 5,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Cerberus's Impetus",
    "rarity": 4,
    "modType": "Melee Consonance Weapon",
    "symbol": "◬",
    "mainAttribute": "ATK +75%",
    "tolerance": 16,
    "track": 5,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Cerberus's Impetus",
    "rarity": 5,
    "modType": "Melee Consonance Weapon",
    "symbol": "◬",
    "mainAttribute": "ATK +81.6%",
    "tolerance": 21,
    "track": 5,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Cerberus's Penetration",
    "rarity": 2,
    "modType": "Melee Consonance Weapon",
    "mainAttribute": "Spike ATK +30%",
    "tolerance": 10,
    "track": 3,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Cerberus's Penetration",
    "rarity": 3,
    "modType": "Melee Consonance Weapon",
    "mainAttribute": "Spike ATK +60%",
    "tolerance": 13,
    "track": 5,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Cerberus's Penetration",
    "rarity": 4,
    "modType": "Melee Consonance Weapon",
    "symbol": "◬",
    "mainAttribute": "Spike ATK +75%",
    "tolerance": 16,
    "track": 5,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Cerberus's Penetration",
    "rarity": 5,
    "modType": "Melee Consonance Weapon",
    "symbol": "◬",
    "mainAttribute": "Spike ATK +81.6%",
    "tolerance": 21,
    "track": 5,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Cerberus's Rage",
    "rarity": 2,
    "modType": "Melee Consonance Weapon",
    "mainAttribute": "CRIT Damage +20%",
    "tolerance": 11,
    "track": 3,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Cerberus's Rage",
    "rarity": 3,
    "modType": "Melee Consonance Weapon",
    "mainAttribute": "CRIT Damage +40%",
    "tolerance": 14,
    "track": 5,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Cerberus's Rage",
    "rarity": 4,
    "modType": "Melee Consonance Weapon",
    "symbol": "◬",
    "mainAttribute": "CRIT Damage +50%",
    "tolerance": 17,
    "track": 5,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Cerberus's Rage",
    "rarity": 5,
    "modType": "Melee Consonance Weapon",
    "symbol": "◬",
    "mainAttribute": "CRIT Damage +54%",
    "tolerance": 22,
    "track": 5,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Cerberus's Threshold",
    "rarity": 2,
    "modType": "Melee Consonance Weapon",
    "mainAttribute": "ATK Range +0.24",
    "tolerance": 15,
    "track": 3,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Cerberus's Threshold",
    "rarity": 3,
    "modType": "Melee Consonance Weapon",
    "mainAttribute": "ATK Range +0.48",
    "tolerance": 18,
    "track": 5,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Cerberus's Threshold",
    "rarity": 4,
    "modType": "Melee Consonance Weapon",
    "symbol": "⊙",
    "mainAttribute": "ATK Range +0.6",
    "tolerance": 21,
    "track": 5,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Cerberus's Threshold",
    "rarity": 5,
    "modType": "Melee Consonance Weapon",
    "symbol": "⊙",
    "mainAttribute": "ATK Range +0.66",
    "tolerance": 26,
    "track": 5,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Cerberus's Trammel",
    "rarity": 3,
    "modType": "Melee Consonance Weapon",
    "mainAttribute": "Trigger Probability +40%",
    "tolerance": 18,
    "track": 5,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Cerberus's Trammel",
    "rarity": 4,
    "modType": "Melee Consonance Weapon",
    "symbol": "☽",
    "mainAttribute": "Trigger Probability +50%",
    "tolerance": 21,
    "track": 5,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Cerberus's Trammel",
    "rarity": 5,
    "modType": "Melee Consonance Weapon",
    "symbol": "☽",
    "mainAttribute": "Trigger Probability +54%",
    "tolerance": 26,
    "track": 5,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Lilith's Celerity",
    "rarity": 2,
    "modType": "Ranged Consonance Weapon",
    "mainAttribute": "ATK Speed +10%",
    "tolerance": 15,
    "track": 3,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Lilith's Celerity",
    "rarity": 3,
    "modType": "Ranged Consonance Weapon",
    "mainAttribute": "ATK Speed +20%",
    "tolerance": 15,
    "track": 5,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Lilith's Celerity",
    "rarity": 4,
    "modType": "Ranged Consonance Weapon",
    "symbol": "⊙",
    "mainAttribute": "ATK Speed +25%",
    "tolerance": 21,
    "track": 5,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Lilith's Celerity",
    "rarity": 5,
    "modType": "Ranged Consonance Weapon",
    "symbol": "⊙",
    "mainAttribute": "ATK Speed +27%",
    "tolerance": 26,
    "track": 5,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Lilith's Crusher",
    "rarity": 2,
    "modType": "Ranged Consonance Weapon",
    "mainAttribute": "Smash ATK +30%",
    "tolerance": 10,
    "track": 3,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Lilith's Crusher",
    "rarity": 3,
    "modType": "Ranged Consonance Weapon",
    "mainAttribute": "Smash ATK +60%",
    "tolerance": 13,
    "track": 5,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Lilith's Crusher",
    "rarity": 4,
    "modType": "Ranged Consonance Weapon",
    "symbol": "◬",
    "mainAttribute": "Smash ATK +75%",
    "tolerance": 16,
    "track": 5,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Lilith's Crusher",
    "rarity": 5,
    "modType": "Ranged Consonance Weapon",
    "symbol": "◬",
    "mainAttribute": "Smash ATK +81.6%",
    "tolerance": 21,
    "track": 5,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Lilith's Edge",
    "rarity": 2,
    "modType": "Ranged Consonance Weapon",
    "mainAttribute": "Slash ATK +30%",
    "tolerance": 10,
    "track": 3,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Lilith's Edge",
    "rarity": 3,
    "modType": "Ranged Consonance Weapon",
    "mainAttribute": "Slash ATK +60%",
    "tolerance": 13,
    "track": 5,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Lilith's Edge",
    "rarity": 4,
    "modType": "Ranged Consonance Weapon",
    "symbol": "◬",
    "mainAttribute": "Slash ATK +75%",
    "tolerance": 16,
    "track": 5,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Lilith's Edge",
    "rarity": 5,
    "modType": "Ranged Consonance Weapon",
    "symbol": "◬",
    "mainAttribute": "Slash ATK +81.6%",
    "tolerance": 21,
    "track": 5,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Lilith's Focus",
    "rarity": 2,
    "modType": "Ranged Consonance Weapon",
    "mainAttribute": "CRIT Chance +20%",
    "tolerance": 11,
    "track": 3,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Lilith's Focus",
    "rarity": 3,
    "modType": "Ranged Consonance Weapon",
    "mainAttribute": "CRIT Chance +40%",
    "tolerance": 14,
    "track": 5,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Lilith's Focus",
    "rarity": 4,
    "modType": "Ranged Consonance Weapon",
    "symbol": "◬",
    "mainAttribute": "CRIT Chance +50%",
    "tolerance": 17,
    "track": 5,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Lilith's Focus",
    "rarity": 5,
    "modType": "Ranged Consonance Weapon",
    "symbol": "◬",
    "mainAttribute": "CRIT Chance +54%",
    "tolerance": 22,
    "track": 5,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Lilith's Foldover",
    "rarity": 2,
    "modType": "Ranged Consonance Weapon",
    "mainAttribute": "Multishot +10%",
    "tolerance": 15,
    "track": 3,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Lilith's Foldover",
    "rarity": 3,
    "modType": "Ranged Consonance Weapon",
    "mainAttribute": "Multishot +20%",
    "tolerance": 18,
    "track": 5,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Lilith's Foldover",
    "rarity": 4,
    "modType": "Ranged Consonance Weapon",
    "symbol": "⊙",
    "mainAttribute": "Multishot +25%",
    "tolerance": 21,
    "track": 5,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Lilith's Foldover",
    "rarity": 5,
    "modType": "Ranged Consonance Weapon",
    "symbol": "⊙",
    "mainAttribute": "Multishot +27%",
    "tolerance": 26,
    "track": 5,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Lilith's Impetus",
    "rarity": 2,
    "modType": "Ranged Consonance Weapon",
    "mainAttribute": "ATK +30%",
    "tolerance": 10,
    "track": 3,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Lilith's Impetus",
    "rarity": 3,
    "modType": "Ranged Consonance Weapon",
    "mainAttribute": "ATK +60%",
    "tolerance": 13,
    "track": 5,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Lilith's Impetus",
    "rarity": 4,
    "modType": "Ranged Consonance Weapon",
    "symbol": "◬",
    "mainAttribute": "ATK +75%",
    "tolerance": 16,
    "track": 5,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Lilith's Impetus",
    "rarity": 5,
    "modType": "Ranged Consonance Weapon",
    "symbol": "◬",
    "mainAttribute": "ATK +81.6%",
    "tolerance": 21,
    "track": 5,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Lilith's Penetration",
    "rarity": 2,
    "modType": "Ranged Consonance Weapon",
    "mainAttribute": "Spike ATK +30%",
    "tolerance": 10,
    "track": 3,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Lilith's Penetration",
    "rarity": 3,
    "modType": "Ranged Consonance Weapon",
    "mainAttribute": "Spike ATK +60%",
    "tolerance": 13,
    "track": 5,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Lilith's Penetration",
    "rarity": 4,
    "modType": "Ranged Consonance Weapon",
    "symbol": "◬",
    "mainAttribute": "Spike ATK +75%",
    "tolerance": 16,
    "track": 5,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Lilith's Penetration",
    "rarity": 5,
    "modType": "Ranged Consonance Weapon",
    "symbol": "◬",
    "mainAttribute": "Spike ATK +81.6%",
    "tolerance": 21,
    "track": 5,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Lilith's Rage",
    "rarity": 2,
    "modType": "Ranged Consonance Weapon",
    "mainAttribute": "CRIT Damage +20%",
    "tolerance": 11,
    "track": 3,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Lilith's Rage",
    "rarity": 3,
    "modType": "Ranged Consonance Weapon",
    "mainAttribute": "CRIT Damage +40%",
    "tolerance": 14,
    "track": 5,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Lilith's Rage",
    "rarity": 4,
    "modType": "Ranged Consonance Weapon",
    "symbol": "◬",
    "mainAttribute": "CRIT Damage +50%",
    "tolerance": 17,
    "track": 5,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Lilith's Rage",
    "rarity": 5,
    "modType": "Ranged Consonance Weapon",
    "symbol": "◬",
    "mainAttribute": "CRIT Damage +54%",
    "tolerance": 22,
    "track": 5,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Lilith's Trammel",
    "rarity": 2,
    "modType": "Ranged Consonance Weapon",
    "mainAttribute": "Trigger Proabability +20%",
    "tolerance": 15,
    "track": 3,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Lilith's Trammel",
    "rarity": 3,
    "modType": "Ranged Consonance Weapon",
    "mainAttribute": "Trigger Proabability +40%",
    "tolerance": 18,
    "track": 5,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Lilith's Trammel",
    "rarity": 4,
    "modType": "Ranged Consonance Weapon",
    "symbol": "☽",
    "mainAttribute": "Trigger Probability +50%",
    "tolerance": 21,
    "track": 5,
    "source": "Shop Exchange"
  },
  {
    "name": "Eldritch Lilith's Trammel",
    "rarity": 5,
    "modType": "Ranged Consonance Weapon",
    "symbol": "☽",
    "mainAttribute": "Trigger Probability +54%",
    "tolerance": 26,
    "track": 5,
    "source": "Shop Exchange"
  },
  {
    "name": "Fafnir's Abundance",
    "rarity": 3,
    "modType": "Ranged Weapon",
    "mainAttribute": "Ammo Conversion Rate +30%",
    "tolerance": 10,
    "track": 5,
    "source": "Level 30"
  },
  {
    "name": "Fafnir's Arrow",
    "rarity": 3,
    "modType": "Ranged Weapon",
    "mainAttribute": "Max Ammo +90%",
    "tolerance": 9,
    "track": 5,
    "source": "Level 30"
  },
  {
    "name": "Fafnir's Carefree",
    "rarity": 3,
    "modType": "Ranged Weapon",
    "mainAttribute": "–",
    "effect": "Upon triggering Bonus Effect, there is 30% chance to reload 1 bullet.",
    "tolerance": 10,
    "track": 5,
    "source": "Level 40"
  },
  {
    "name": "Fafnir's Coercion",
    "rarity": 3,
    "modType": "Ranged Weapon",
    "mainAttribute": "Projectile Explosion Range +1.5",
    "tolerance": 15,
    "track": 5,
    "source": "Level 40"
  },
  {
    "name": "Fafnir's Decline",
    "rarity": 3,
    "modType": "Ranged Weapon",
    "mainAttribute": "–",
    "effect": "When dealing CRIT Damage, there is 100% chance to disarm the target.",
    "tolerance": 8,
    "track": 5,
    "source": "Level 40"
  },
  {
    "name": "Fafnir's Dexterity",
    "rarity": 3,
    "modType": "Ranged Weapon",
    "mainAttribute": "Reload Speed +30%",
    "tolerance": 9,
    "track": 5,
    "source": "Level 30"
  },
  {
    "name": "Fafnir's Divine Herald Hunt",
    "rarity": 4,
    "modType": "Ranged Weapon",
    "symbol": "◬",
    "mainAttribute": "–",
    "effect": "Increase Damage Dealt to The Elysian Church by 40%",
    "tolerance": 14,
    "track": 5,
    "source": "Level 65"
  },
  {
    "name": "Fafnir's Filthoid Hunt",
    "rarity": 4,
    "modType": "Ranged Weapon",
    "symbol": "◬",
    "mainAttribute": "–",
    "effect": "Increase Damage Dealt to Filthoid by 40%",
    "tolerance": 14,
    "track": 5,
    "source": "Level 65"
  },
  {
    "name": "Fafnir's Focus",
    "rarity": 4,
    "modType": "Ranged Weapon",
    "symbol": "⊙",
    "mainAttribute": "–",
    "effect": "Beam Length +50%",
    "tolerance": 17,
    "track": 5,
    "source": "Level 55, Level 60"
  },
  {
    "name": "Fafnir's Forsaken Hunt",
    "rarity": 4,
    "modType": "Ranged Weapon",
    "symbol": "◬",
    "mainAttribute": "–",
    "effect": "Increase Damage Dealt to The Forsakens by 40%",
    "tolerance": 14,
    "track": 5,
    "source": "Level 60"
  },
  {
    "name": "Fafnir's Frugality",
    "rarity": 4,
    "modType": "Ranged Weapon",
    "symbol": "◊",
    "mainAttribute": "–",
    "effect": "When dealing damage, increase the damage according to the percentage of the remaining projectiles. The higher the percentage, the greater the increase, up to 30%.",
    "tolerance": 17,
    "track": 5,
    "source": "Level 50"
  },
  {
    "name": "Fafnir's Furious Beam",
    "rarity": 4,
    "modType": "Ranged Weapon",
    "symbol": "⊙",
    "mainAttribute": "–",
    "effect": "Increase beam damage by 20%",
    "tolerance": 20,
    "track": 5,
    "source": "Level 55"
  },
  {
    "name": "Fafnir's Furious Blast",
    "rarity": 4,
    "modType": "Ranged Weapon",
    "symbol": "⊙",
    "mainAttribute": "–",
    "effect": "Increase explosive projectile damage by 20%",
    "tolerance": 20,
    "track": 5,
    "source": "Level 55"
  },
  {
    "name": "Fafnir's Hunt",
    "rarity": 3,
    "modType": "Ranged Weapon",
    "mainAttribute": "–",
    "effect": "When triggering Bonus Effect, gain 1 stack that increases Multishot by 10% for 10s, up to 5 stacks.",
    "tolerance": 12,
    "track": 5,
    "source": "Level 40"
  },
  {
    "name": "Fafnir's Legion Hunt",
    "rarity": 4,
    "modType": "Ranged Weapon",
    "symbol": "◬",
    "mainAttribute": "–",
    "effect": "Increase Damage Dealt to Hyperborean Soldier by 40%",
    "tolerance": 14,
    "track": 5,
    "source": "Level 65"
  },
  {
    "name": "Fafnir's Lingering Might",
    "rarity": 3,
    "modType": "Ranged Weapon",
    "mainAttribute": "–",
    "effect": "Triggers an explosion at the targt location upon defeating enemy, dealing 15% of your Ranged Weapon damage to enemies within 6 metre range.",
    "tolerance": 10,
    "track": 5,
    "source": "Level 40"
  },
  {
    "name": "Fafnir's Loadout",
    "rarity": 4,
    "modType": "Ranged Weapon",
    "symbol": "◊",
    "mainAttribute": "–",
    "effect": "After reloading, increases ATK Speed by 45% for 10s.",
    "tolerance": 15,
    "track": 5,
    "source": "Level 50"
  },
  {
    "name": "Fafnir's Pierce",
    "rarity": 4,
    "modType": "Ranged Weapon",
    "symbol": "◬",
    "mainAttribute": "HP Reduce on Bonus Effect: Spike +80%.",
    "tolerance": 14,
    "track": 5,
    "source": "Level 60"
  },
  {
    "name": "Fafnir's Quiver",
    "rarity": 3,
    "modType": "Ranged Weapon",
    "mainAttribute": "Mag Capacity +30%",
    "tolerance": 9,
    "track": 5,
    "source": "Level 30"
  },
  {
    "name": "Fafnir's Severance",
    "rarity": 4,
    "modType": "Ranged Weapon",
    "symbol": "◬",
    "mainAttribute": "Shield Reduce on Bonus Effect: Slash +80%.",
    "tolerance": 14,
    "track": 5,
    "source": "Level 55"
  },
  {
    "name": "Fafnir's Speed Boost",
    "rarity": 4,
    "modType": "Ranged Weapon",
    "symbol": "⊙",
    "mainAttribute": "Projectile SPD +60%",
    "tolerance": 15,
    "track": 5,
    "source": "Level 60"
  },
  {
    "name": "Fafnir's Stall",
    "rarity": 4,
    "modType": "Ranged Weapon",
    "symbol": "⊙",
    "mainAttribute": "Projectile SPD -60%",
    "tolerance": 15,
    "track": 5,
    "source": "Level 60"
  },
  {
    "name": "Fafnir's Tyranny",
    "rarity": 3,
    "modType": "Ranged Weapon",
    "mainAttribute": "–",
    "effect": "When dealing CRIT Damage, gains 1 stack that increases Trigger Probability by 30% for 5s, up to 5 stacks.",
    "tolerance": 10,
    "track": 5,
    "source": "Level 40"
  }
].map(mod => ({ ...mod, image: getModImage(mod.name, mod.element) } as Mod));

// Mock Builds - updated to use new characters and weapons
export const builds: Build[] = [
  {
    id: '1',
    userId: 'mock-user-1',
    buildName: 'Volcanic Onslaught',
    description: 'Focuses on rapid, high-damage strikes infused with Pyro, overwhelming enemies before they can react.',
    guide: 'Use Pyro infusion to maximize damage output. Focus on building CRIT Rate and CRIT DMG. Rotate through team members to maintain buffs.',
    visibility: 'public',
    itemType: 'character',
    itemId: allCharacters.find(c => c.name === 'Lynn')!.id,
    itemName: 'Lynn',
    itemImage: allCharacters.find(c => c.name === 'Lynn')!.image,
    creator: 'AshenOne',
    mods: [],
    team: [
      allCharacters.find(c => c.name === 'Rebecca')!,
      allCharacters.find(c => c.name === 'Psyche')!,
      allCharacters.find(c => c.name === 'Randy')!
    ].filter(Boolean).map(c => c.id),
    supportWeapons: [],
    supportMods: {},
    voteCount: 1254,
    votedBy: [],
    views: 25300,
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    // Legacy fields for compatibility
    character: allCharacters.find(c => c.name === 'Lynn')!,
    weapon: allMeleeWeapons.find(w => w.name === 'Punitive Inferno')!,
    upvotes: 1254,
    contentFocus: ['DPS (Weapon DMG)'],
  },
  {
    id: '2',
    userId: 'mock-user-2',
    buildName: 'Abyssal Summoner',
    description: 'Provides consistent off-field Hydro application and bursts of damage, enabling powerful elemental reactions.',
    guide: 'Focus on Summon damage and Hydro application. Build HP% for stronger summons. Use skill rotation to maintain constant pressure.',
    visibility: 'public',
    itemType: 'character',
    itemId: allCharacters.find(c => c.name === 'Rebecca')!.id,
    itemName: 'Rebecca',
    itemImage: allCharacters.find(c => c.name === 'Rebecca')!.image,
    creator: 'TideCaller',
    mods: [],
    team: [
      allCharacters.find(c => c.name === 'Lynn')!,
      allCharacters.find(c => c.name === 'Sibylle')!,
      allCharacters.find(c => c.name === 'Psyche')!
    ].filter(Boolean).map(c => c.id),
    supportWeapons: [],
    supportMods: {},
    voteCount: 980,
    votedBy: [],
    views: 18900,
    createdAt: new Date(Date.now() - 86400000 * 6).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    // Legacy fields for compatibility
    character: allCharacters.find(c => c.name === 'Rebecca')!,
    weapon: allMeleeWeapons.find(w => w.name === "Siren's Kiss")!,
    upvotes: 980,
    contentFocus: ['DPS (Skill DMG, Summon)', 'Support (Summon, CC)'],
  },
];