import type { Weapon } from './types';

// Extended weapon data with detailed stats and passive effects
export const weaponDetails: Record<string, Partial<Weapon>> = {
  // Melee Weapons
  'aureate-yore': {
    element: 'Neutral',
    skillType: 'Skill',
    passiveEffect: 'CRIT Damage (+62.5% / 74.4% / 86.8% / 99.2% / 112.5% / 125%). Sliding attacks with this weapon gain (+75% / 90% / 105% / 120% / 135% / 150%) CRIT Chance.',
    stats: {
      critChance: '24%',
      critDamage: '215%',
      atkSpeed: 1,
      triggerProbability: '15%',
    },
    attributes: {
      '1-Hit DMG': '20% x 2',
      '2-Hit DMG': '25% x 2',
      '3-Hit DMG': '38%',
      '4-Hit DMG': '43% x 3',
      'Charged Attack DMG': '20% x 6',
      'Charged Attack Finisher DMG': '55%',
      'Plunge DMG': '51%',
      'Sliding Attack DMG': '36% x 2',
    },
  },
  'blade-amberglow': {
    element: 'Neutral',
    skillType: 'Skill',
    passiveEffect: 'Character ATK (+60% / 72% / 84% / 96% / 108% / 120%).',
    stats: {
      critChance: '25%',
      critDamage: '200%',
      atkSpeed: 1,
      triggerProbability: '15%',
    },
    attributes: {
      '1-Hit DMG': '45%',
      '2-Hit DMG': '50%',
      '3-Hit DMG': '40% x 2',
      '4-Hit DMG': '82%',
      'Charged Attack DMG': '113%',
      'Plunge DMG': '51%',
      'Sliding Attack DMG': '51%',
    },
  },
  'elpides-abound': {
    element: 'Anemo',
    skillType: 'Skill',
    passiveEffect: 'Resolve (+5.0% / 6% / 7% / 8% / 9% / 10%). After an Anemo character uses their Ultimate Skill, grants [Thousand Winds\' Blessing]: increases Resolve by (8.0% / 9.6% / 11.2% / 12.8% / 14.4% / 16%) and ATK Speed by (15.0% / 18% / 21% / 24% / 27% / 30%) for 15.0s. Each instance of Skill Damage or Ranged Weapon Damage extends the duration by 0.2s.',
    stats: {
      critChance: '23%',
      critDamage: '250%',
      atkSpeed: 1,
      triggerProbability: '10%',
    },
    attributes: {
      '1-Hit DMG': '35%',
      '2-Hit DMG': '25% x 3',
      '3-Hit DMG': '50%',
      '4-Hit DMG': '40%',
      '5-Hit DMG': '75%',
      'Charged Attack DMG': '10%',
      'Plunge DMG': '47%',
      'Sliding Attack DMG': '40%',
    },
  },
  'exiled-fangs': {
    element: 'Neutral',
    skillType: 'Skill',
    passiveEffect: 'ATK Speed (+25% / 30% / 35% / 40% / 45% / 50%). When dealing damage with this weapon triggers Bonus Effect, if the user\'s HP percentage is below 25%, there\'s a 45% chance to restore (1.5% / 1.8% / 2.1% / 2.4% / 3.7% / 3%) of the character\'s Max HP.',
    stats: {
      critChance: '16%',
      critDamage: '210%',
      atkSpeed: 1,
      triggerProbability: '33%',
    },
    attributes: {
      '1-Hit DMG': '20% x 2',
      '2-Hit DMG': '25% x 2',
      '3-Hit DMG': '38%',
      '4-Hit DMG': '43% x 3',
      'Charged Attack DMG': '20% x 6',
      'Charged Attack Finisher DMG': '55%',
      'Plunge DMG': '51%',
      'Sliding Attack DMG': '36% x 2',
    },
  },
  'fathomless-sharkgaze': {
    element: 'Neutral',
    skillType: 'Skill',
    passiveEffect: 'Skill Range (+36% / 43.2% / 50.4% / 57.6% / 64.8% / 72%).',
    stats: {
      critChance: '20%',
      critDamage: '235%',
      atkSpeed: 1,
      triggerProbability: '28%',
    },
    attributes: {
      '1-Hit DMG': '20% x 2',
      '2-Hit DMG': '25% x 2',
      '3-Hit DMG': '38%',
      '4-Hit DMG': '43% x 3',
      'Charged Attack DMG': '20% x 6',
      'Charged Attack Finisher DMG': '55%',
      'Plunge DMG': '51%',
      'Sliding Attack DMG': '36% x 2',
    },
  },
  'ingenious-tactics': {
    element: 'Neutral',
    skillType: 'Skill',
    passiveEffect: 'DEF (+50% / 60% / 70% / 80% / 90% / 100%). When dealing damage with this weapon triggers Bonus Effect, there\'s a (25% / 30% / 35% / 40% / 45% / 50%) chance to decrease the target\'s Shield by 350% of the user\'s DEF.',
    stats: {
      critChance: '20%',
      critDamage: '200%',
      atkSpeed: 1,
      triggerProbability: '33%',
    },
    attributes: {
      '1-Hit DMG': '45%',
      '2-Hit DMG': '50%',
      '3-Hit DMG': '40% x 2',
      '4-Hit DMG': '82%',
      'Charged Attack DMG': '113%',
      'Plunge DMG': '51%',
      'Sliding Attack DMG': '51%',
    },
  },
  'ironforger': {
    element: 'Neutral',
    skillType: 'Skill',
    passiveEffect: 'CRIT Chance (+50% / 60% / 70% / 80% / 90% / 100%). When dealing damage with this weapon triggers Bonus Effect, there is a (2.1% / 2.94% / 3.36% / 3.78% / 4.2%) chance to increase the Combo Level to maximum.',
    stats: {
      critChance: '30%',
      critDamage: '205%',
      atkSpeed: 1,
      triggerProbability: '30%',
    },
    attributes: {
      '1-Hit DMG': '40%',
      '2-Hit DMG': '45%',
      '3-Hit DMG': '50%',
      '4-Hit DMG': '120%',
      'Charged Attack DMG': '55%',
      'Charged Attack Finisher DMG': '50%',
      'Plunge DMG': '51%',
      'Sliding Attack DMG': '73%',
    },
  },
  'momiji-itteki': {
    element: 'Neutral',
    skillType: 'Skill',
    passiveEffect: 'CRIT Damage (+62.5% / 74.4% / 86.8% / 99.2% / 112.5% / 125%). When dealing damage with this weapon, increase Damage Dealt by (9.0% / 10.8% / 12.6% / 14.4% / 16.2% / 18%), with an additional 9.0% increase per Combo Level.',
    stats: {
      critChance: '22%',
      critDamage: '225%',
      atkSpeed: 1,
      triggerProbability: '15%',
    },
    attributes: {
      '1-Hit DMG': '20% x 3',
      '2-Hit DMG': '30% x 4',
      '3-Hit DMG': '40% x 2 + 45%',
      '4-Hit DMG': '85%',
      'Charged Attack DMG': '10% x 9',
      'Plunge DMG': '51%',
      'Sliding Attack DMG': '51%',
    },
  },
  'punitive-inferno': {
    element: 'Pyro',
    skillType: 'Skill',
    passiveEffect: 'Max HP (+50% / 60% / 70% / 80% / 90% / 100%). When a Pyro character takes damage, grants (+15% / 18% / 21% / 24% / 27% / 30%) Skill Duration for 8s (up to 3 stacks).',
    stats: {
      critChance: '24%',
      critDamage: '205%',
      atkSpeed: 1,
      triggerProbability: '15%',
    },
    attributes: {
      '1-Hit DMG': '40%',
      '2-Hit DMG': '45%',
      '3-Hit DMG': '50%',
      '4-Hit DMG': '120%',
      'Charged Attack DMG': '55%',
      'Charged Attack Finisher DMG': '50%',
      'Plunge DMG': '51%',
      'Sliding Attack DMG': '73%',
    },
  },
  'pyrothirst': {
    element: 'Neutral',
    skillType: 'Skill',
    passiveEffect: 'Skill Duration (+18% / 21.6% / 25.2% / 28.8% / 32.4% / 36%).',
    stats: {
      critChance: '24%',
      critDamage: '210%',
      atkSpeed: 1,
      triggerProbability: '20%',
    },
    attributes: {
      '1-Hit DMG': '40%',
      '2-Hit DMG': '45%',
      '3-Hit DMG': '50%',
      '4-Hit DMG': '120%',
      'Charged Attack DMG': '55%',
      'Charged Attack Finisher DMG': '50%',
      'Plunge DMG': '51%',
      'Sliding Attack DMG': '73%',
    },
  },
  'remanent-reminiscence': {
    element: 'Neutral',
    skillType: 'Skill',
    passiveEffect: 'ATK Range (+1.0 / 1.2 / 1.4 / 1.6 / 2.0). Landing a CRIT with this weapon has a (33.0% / 39.6% / 46.2% / 52.8% / 59.4% / 66%) chance to restore 3.0 Sanity. Can trigger once every 0.5s.',
    stats: {
      critChance: '30%',
      critDamage: '210%',
      atkSpeed: 1,
      triggerProbability: '12%',
      atkRange: 1,
    },
    attributes: {
      '1-Hit DMG': '45%',
      '2-Hit DMG': '50%',
      '3-Hit DMG': '40% x 2',
      '4-Hit DMG': '82%',
      'Charged Attack DMG': '113%',
      'Plunge DMG': '51%',
      'Sliding Attack DMG': '51%',
    },
  },
  'sacred-favour': {
    element: 'Neutral',
    skillType: 'Skill',
    passiveEffect: 'Character ATK (+50.0% / 60% / 70% / 80% / 90% / 100%). Charged Attacks with this weapon grant (+75.0% / 90% / 105% / 120% / 135% / 150%) CRIT Damage for 6.0s. Effect is removed when switching weapons.',
    stats: {
      critChance: '20%',
      critDamage: '250%',
      atkSpeed: 1,
      triggerProbability: '20%',
    },
    attributes: {
      '1-Hit DMG': '20% x 3',
      '2-Hit DMG': '30% x 4',
      '3-Hit DMG': '40% x 2 + 45%',
      '4-Hit DMG': '85%',
      'Charged Attack DMG': '10% x 9',
      'Plunge DMG': '51%',
      'Sliding Attack DMG': '51%',
    },
  },
  'shackle-of-lonewolf': {
    element: 'Hydro',
    skillType: 'Skill',
    passiveEffect: 'Trigger Probability (+75.0% / 90% / 105% / 120% / 135% / 150%). When a Hydro character triggers a bonus effect with this weapon, other allies gain (+33.0% / 39.6% / 46.2% / 52.8% / 59.4% / 66%) ATK for 6.0s.',
    stats: {
      critChance: '22%',
      critDamage: '215%',
      atkSpeed: 1,
      triggerProbability: '30%',
    },
    attributes: {
      '1-Hit DMG': '45%',
      '2-Hit DMG': '50%',
      '3-Hit DMG': '40% x 2',
      '4-Hit DMG': '82%',
      'Charged Attack DMG': '113%',
      'Plunge DMG': '51%',
      'Sliding Attack DMG': '51%',
    },
  },
  'sirens-kiss': {
    element: 'Neutral',
    skillType: 'Skill',
    passiveEffect: 'Skill Range (+30% / 36% / 42% / 48% / 54% / 60%). When performing Normal Attacks with this weapon, grants a (3.6% / 4.32% / 5.04% / 5.76% / 6.48% / 7.2%) ATK Speed Increase for 15.0s (up to 12.0 stacks). Effect is removed when switching weapons.',
    stats: {
      critChance: '22%',
      critDamage: '220%',
      atkSpeed: 1,
      triggerProbability: '22%',
    },
    attributes: {
      '1-Hit DMG': '35%',
      '2-Hit DMG': '25% x 3',
      '3-Hit DMG': '50%',
      '4-Hit DMG': '40%',
      '5-Hit DMG': '75%',
      'Charged Attack DMG': '10%',
      'Plunge DMG': '47%',
      'Sliding Attack DMG': '40%',
    },
  },
  'tetherlash': {
    element: 'Neutral',
    skillType: 'Skill',
    passiveEffect: 'Skill Duration (+18% / 21.6% / 25.2% / 28.8% / 32.4% / 36%).',
    stats: {
      critChance: '18%',
      critDamage: '215%',
      atkSpeed: 1,
      triggerProbability: '30%',
    },
    attributes: {
      '1-Hit DMG': '40%',
      '2-Hit DMG': '50%',
      '3-Hit DMG': '60%',
      '4-Hit DMG': '50% x 2',
      'Charged Attack DMG': '16.1%',
      'Plunge DMG': '51%',
      'Sliding Attack DMG': '51%',
    },
  },
  'undying-oneiros': {
    element: 'Neutral',
    skillType: 'Skill',
    passiveEffect: 'Max HP (+50.0% / 60% / 70% / 80% / 90% / 100%). When this weapon triggers a bonus effect on hit, grants (+8.6% / 10.32% / 12.04% / 13.76% / 15.48% / 17.2%) Max HP for 15.0s (up to 10.0 stacks).',
    stats: {
      critChance: '20%',
      critDamage: '225%',
      atkSpeed: 1,
      triggerProbability: '30%',
    },
    attributes: {
      '1-Hit DMG': '40%',
      '2-Hit DMG': '50%',
      '3-Hit DMG': '60%',
      '4-Hit DMG': '50% x 2',
      'Charged Attack DMG': '16.1%',
      'Plunge DMG': '51%',
      'Sliding Attack DMG': '51%',
    },
  },
  'vernal-jade-halberd': {
    element: 'Neutral',
    skillType: 'Skill',
    passiveEffect: 'ATK Speed (+25.0% / 30% / 35% / 40% / 45% / 50%). Deals (+45.0% / 54% / 63% / 72% / 81% / 90%) damage to targets afflicted with bonus effects.',
    stats: {
      critChance: '24%',
      critDamage: '215%',
      atkSpeed: 1,
      triggerProbability: '30%',
    },
    attributes: {
      '1-Hit DMG': '35%',
      '2-Hit DMG': '25% x 3',
      '3-Hit DMG': '50%',
      '4-Hit DMG': '40%',
      '5-Hit DMG': '75%',
      'Charged Attack DMG': '10%',
      'Plunge DMG': '47%',
      'Sliding Attack DMG': '40%',
    },
  },
  'viridis-reefs': {
    element: 'Neutral',
    skillType: 'Skill',
    passiveEffect: 'Trigger Probability (+75.0% / 90% / 105% / 120% / 135% / 150%). Charged Attacks with this weapon grants (+44.0% / 52.8% / 61.6% / 70.4% / 79.2% / 88%) ATK Speed for 6.0s. Effect is removed when switching weapons.',
    stats: {
      critChance: '26%',
      critDamage: '235%',
      atkSpeed: 1,
      triggerProbability: '12%',
    },
    attributes: {
      '1-Hit DMG': '40%',
      '2-Hit DMG': '50%',
      '3-Hit DMG': '60%',
      '4-Hit DMG': '50% x 2',
      'Charged Attack DMG': '16.1%',
      'Plunge DMG': '51%',
      'Sliding Attack DMG': '51%',
    },
  },
  'wandering-rose': {
    element: 'Neutral',
    skillType: 'Skill',
    passiveEffect: 'ATK Speed (+25.0% / 30% / 35% / 40% / 45% / 50%). When a performing a Charged Attack with this weapon, there is a (28.0% / 33.6% / 39.2% / 44.8% / 50.4% / 56%) chance to reduce Resonance Support CD by 3.0s.',
    stats: {
      critChance: '23%',
      critDamage: '210%',
      atkSpeed: 1,
      triggerProbability: '28%',
    },
    attributes: {
      '1-Hit DMG': '45%',
      '2-Hit DMG': '50%',
      '3-Hit DMG': '40% x 2',
      '4-Hit DMG': '82%',
      'Charged Attack DMG': '113%',
      'Plunge DMG': '51%',
      'Sliding Attack DMG': '51%',
    },
  },
  'wanewraith': {
    element: 'Neutral',
    skillType: 'Skill',
    passiveEffect: 'Skill Damage (+24% / 28.8% / 33.6% / 38.4% / 43.2% / 48%).',
    stats: {
      critChance: '25%',
      critDamage: '200%',
      atkSpeed: 1,
      triggerProbability: '15%',
    },
    attributes: {
      '1-Hit DMG': '35%',
      '2-Hit DMG': '25% x 3',
      '3-Hit DMG': '50%',
      '4-Hit DMG': '40%',
      '5-Hit DMG': '75%',
      'Charged Attack DMG': '10%',
      'Plunge DMG': '47%',
      'Sliding Attack DMG': '40%',
    },
  },
  'withershade': {
    element: 'Neutral',
    skillType: 'Skill',
    passiveEffect: 'Skill Range (+36% / 43.2% / 50.4% / 57.6% / 64.8% / 72%).',
    stats: {
      critChance: '23%',
      critDamage: '215%',
      atkSpeed: 1,
      triggerProbability: '20%',
    },
    attributes: {
      '1-Hit DMG': '20% x 3',
      '2-Hit DMG': '30% x 4',
      '3-Hit DMG': '40% x 2 + 45%',
      '4-Hit DMG': '85%',
      'Charged Attack DMG': '10% x 9',
      'Plunge DMG': '51%',
      'Sliding Attack DMG': '51%',
    },
  },
  // Ranged Weapons
  'arclight-apocalypses': {
    element: 'Neutral',
    skillType: 'Skill',
    passiveEffect: 'Skill Duration (+15% / 18% / 21% / 24% / 27% / 30%). Landing a CRIT hit with this weapon randomly grants other allies one of the following for 16s: (+10% / 12% / 14% / 16% / 18% / 20%) ATK, (+10% / 12% / 14% / 16% / 18% / 20%) DEF, (+7.5% / 9% / 10.5% / 12% / 13.5% / 15%) Skill Damage or (+10% / 12% / 14% / 16% / 18% / 20%) Skill Duration.',
    stats: {
      critChance: '26%',
      critDamage: '220%',
      atkSpeed: 1,
      triggerProbability: '20%',
      multishot: 1,
      maxAmmo: 150,
      ammoConversionRate: '475%',
    },
    attributes: {
      'Projectile Damage': '6.3%',
      'Number of Projectiles': 7,
    },
  },
  'blast-artistry': {
    element: 'Neutral',
    skillType: 'Skill',
    passiveEffect: 'Character ATK (+50.0% / 60% / 70% / 80% / 90% / 100%). Charging fires a special bullet that travels slowly and explodes after a short delay, dealing AoE damage. Tap-firing bullets can trigger its early detonation on contact. When an Umbro character casts their Ultimate, grants (+20.0% / 24% / 28% / 32% / 36% / 40%) Skill Efficiency for 15.0s',
    stats: {
      critChance: '15%',
      critDamage: '165%',
      atkSpeed: 1,
      triggerProbability: '10%',
      multishot: 1,
      magCapacity: 12,
      maxAmmo: 60,
      ammoConversionRate: '30%',
    },
    attributes: {
      'Projectile DMG': '33%',
      'Explosion DMG': '200%',
      'Projectile Calibre': '2.8m',
    },
  },
  'bluecurrent-pulse': {
    element: 'Neutral',
    skillType: 'Skill',
    passiveEffect: 'Skill Duration (+15% / 18% / 21% / 24% / 27% / 30%). When its projectiles hit enemies or the environment, they bounce once. When dealing damage with this weapon, increases Dual Pistols Damage by (45% / 54% / 63% / 72% / 81% / 90%) for (15s / 18s / 21s / 24s / 27s / 30s).',
    stats: {
      critChance: '20%',
      critDamage: '225%',
      atkSpeed: 1,
      triggerProbability: '25%',
      multishot: 1,
      magCapacity: 20,
      maxAmmo: 150,
      ammoConversionRate: '60%',
    },
    attributes: {
      'Projectile DMG': '47%',
      'Ricochet DMG': '47%',
    },
  },
  'day-of-sacred-verdict': {
    element: 'Neutral',
    skillType: 'Skill',
    passiveEffect: 'CRIT Damage (+62.5% / 75% / 87.5% / 100% / 112.5% / 125%). Fired projectiles track the crosshair. When dealing damage with this weapon, the farther the target, the higher the damage, up to a maximum increase of (45.0% / 54% / 63% / 72% / 81% / 90%).',
    stats: {
      critChance: '20%',
      critDamage: '200%',
      atkSpeed: 1,
      triggerProbability: '15%',
      multishot: 1,
      magCapacity: 5,
      maxAmmo: 60,
      ammoConversionRate: '25%',
    },
    attributes: {
      'Explosion DMG': '139%',
      'Explosion Radius': '3m',
    },
  },
  'daybreak-hymn': {
    element: 'Neutral',
    skillType: 'Skill',
    passiveEffect: 'Multishot (+37.5% / 45% / 52.5% / 60% / 67.5% / 75%). When dealing damage with this weapon, the lower the remaining Ammo percentage, the higher the damage dealt, up to a maximum increase of (45% / 54% / 63% / 72% / 81% / 90%), with full effect when the Ammo count is below 20%.',
    stats: {
      critChance: '26%',
      critDamage: '245%',
      atkSpeed: 1,
      triggerProbability: '24%',
      multishot: 1,
      magCapacity: 30,
      maxAmmo: 100,
      ammoConversionRate: '110%',
    },
    attributes: {
      'Beam Damage': '12%',
      'Beam DMG - Phase 2': '20%',
      'Beam DMG - Phase 3': '37%',
      'Firing Interval': '0.5 shots/s',
      'Firing Interval - Phase 2': '0.35 shots/s',
      'Firing Interval - Phase 3': '0.1 shots/s',
    },
  },
  'destructo': {
    element: 'Neutral',
    skillType: 'Skill',
    passiveEffect: 'Skill Range (+36% / 43.2% / 50.4% / 57.6% / 64.8% / 72%).',
    stats: {
      critChance: '20%',
      critDamage: '180%',
      atkSpeed: 1,
      triggerProbability: '20%',
      multishot: 1,
      magCapacity: 8,
      maxAmmo: 40,
      ammoConversionRate: '35%',
    },
    attributes: {
      'Explosion DMG': '95%',
      'Explosion Radius': '3m',
    },
  },
  'dreamweavers-feather': {
    element: 'Lumino',
    skillType: 'Skill',
    passiveEffect: 'Skill Range +(30% / 36% / 42% / 48% / 54% / 60%). When a Lumino character deals additional damage, it will have a 30% chance to grant 1 stack that increases ATK for the nearby teammates by (9% / 10.8% / 12.6% / 14.4% / 16.2% / 18%) for 15s, up to 10 stacks.',
    stats: {
      critChance: '24%',
      critDamage: '240%',
      atkSpeed: 1,
      triggerProbability: '15%',
      multishot: 1,
      magCapacity: 50,
      maxAmmo: 120,
      ammoConversionRate: '150%',
    },
    attributes: {
      'Beam Damage': '20%',
      'Firing Interval': '0.13 shots/s',
    },
  },
  'embla-inflorescence': {
    element: 'Lumino',
    skillType: 'Skill',
    passiveEffect: 'Skill Range (+30% / 36% / 42% / 48% / 54% / 60%). While charging, gradually locks onto nearby enemies. Upon release, fires tracking arrows at all locked targets. When a Lumino character deals Skill Damage, grants (+35% / 42% / 49% / 56% / 63% / 70%) Skill DMG for 6s.',
    stats: {
      critChance: '22%',
      critDamage: '220%',
      atkSpeed: 1,
      triggerProbability: '30%',
      multishot: 1,
      maxAmmo: 150,
      ammoConversionRate: '125%',
    },
    attributes: {
      'Projectile DMG': '18%',
      'Projectile Calibre': '0.2m',
    },
  },
  'entropic-singularity': {
    element: 'Neutral',
    skillType: 'Skill',
    passiveEffect: 'Trigger Probability (+75.0% / 90% / 105% / 120% / 135% / 150%). Each shot with this weapon has a chance (based on its Weapon Trigger Probability) to fire an extra projectile at no Ammo cost, dealing AoE Damage equal to (50.0% / 60% / 70% / 80% / 90% / 100%) of its ATK.',
    stats: {
      critChance: '20%',
      critDamage: '210%',
      atkSpeed: 1,
      triggerProbability: '33%',
      multishot: 1,
      magCapacity: 20,
      maxAmmo: 150,
      ammoConversionRate: '40%',
    },
    attributes: {
      'Projectile DMG': '71%',
      'Explosion DMG': '50%',
      'Explosion Radius': '3m',
    },
  },
  'excresduo': {
    element: 'Neutral',
    skillType: 'Skill',
    passiveEffect: 'Skill Damage (+24% / 28.8% / 33.6% / 38.4% / 43.2% / 48%).',
    stats: {
      critChance: '20%',
      critDamage: '220%',
      atkSpeed: 1,
      triggerProbability: '28%',
      multishot: 1,
      magCapacity: 20,
      maxAmmo: 150,
      ammoConversionRate: '60%',
    },
    attributes: {
      'Projectile DMG': '47%',
    },
  },
  'exiled-thunderwyrm': {
    element: 'Electro',
    skillType: 'Skill',
    passiveEffect: 'Trigger Probability (+75% / 90% / 105% / 120% / 135% / 150%). Fires a beam that can ricochet off the target and hits up to 4 enemies within range. When an Electro character triggers bonus effects with this weapon, the user gains (+45% / 54% / 63% / 81% / 90%) Skill Damage for 10s.',
    stats: {
      critChance: '25%',
      critDamage: '220%',
      atkSpeed: 1,
      triggerProbability: '15%',
      multishot: 1,
      magCapacity: 30,
      maxAmmo: 160,
      ammoConversionRate: '160%',
    },
    attributes: {
      'Beam Damage': '17.6%',
      'Ricochet DMG': '17.6%',
      'Firing Interval': '0.1 shots/s',
    },
  },
  'flamme-de-epuration': {
    element: 'Neutral',
    skillType: 'Skill',
    passiveEffect: 'Trigger Probability (+75% / 90% / 105% / 120% / 135% / 150%). When this weapon triggers a bonus effect on hit, there is (30% / 36% / 42% / 48% / 54% / 60%) chance to reload 1 projectile.',
    stats: {
      critChance: '15%',
      critDamage: '200%',
      atkSpeed: 1,
      triggerProbability: '33%',
      multishot: 1,
      magCapacity: 50,
      maxAmmo: 120,
      ammoConversionRate: '150%',
    },
    attributes: {
      'Beam Damage': '20%',
      'Firing Interval': '0.13 shots/s',
    },
  },
  'guixu-ratchet': {
    element: 'Neutral',
    skillType: 'Skill',
    passiveEffect: 'CRIT Damage (+62.5% / 75% / 87.5% / 100% / 112.5% / 125%). When its projectiles hit enemies or the environment, they split into 2 additional projectiles that continue to travel. After switching to this weapon, increases Multishot by (38.0% / 45.6% / 53.2% / 60.8% / 68.4% / 73%), which decreases over time. This effect can only be triggered once every 10s and is removed when switching to another weapon.',
    stats: {
      critChance: '22%',
      critDamage: '215%',
      atkSpeed: 1,
      triggerProbability: '20%',
      multishot: 1,
      magCapacity: 8,
      maxAmmo: 20,
      ammoConversionRate: '30%',
    },
    attributes: {
      'Explosion DMG': '15%',
      'DoT': '4%',
      'Explosion DMG - Phase 2': '8%',
      'Explosion Radius': '3m',
      '2-Hit Explosion Radius': '3m',
    },
  },
  'osteobreaker': {
    element: 'Neutral',
    skillType: 'Skill',
    passiveEffect: 'Skill Duration (+18% / 21.6% / 25.2% / 28.8% / 32.4% / 36%).',
    stats: {
      critChance: '23%',
      critDamage: '225%',
      atkSpeed: 1,
      triggerProbability: '30%',
      multishot: 1,
      magCapacity: 50,
      maxAmmo: 200,
      ammoConversionRate: '200%',
    },
    attributes: {
      'Projectile Damage': '16%',
      'Firing Interval': '0.1 shots/s',
    },
  },
  'rendhusk': {
    element: 'Neutral',
    skillType: 'Skill',
    passiveEffect: 'Character ATK (+60% / 62% / 84% / 96% / 108% / 120%).',
    stats: {
      critChance: '25%',
      critDamage: '230%',
      atkSpeed: 1,
      triggerProbability: '15%',
      multishot: 1,
      magCapacity: 15,
      maxAmmo: 150,
      ammoConversionRate: '40%',
    },
    attributes: {
      'Projectile DMG': '71%',
    },
  },
  'sacrosanct-chorus': {
    element: 'Neutral',
    skillType: 'Skill',
    passiveEffect: 'CRIT Chance (+50% / 60% / 70% / 80% / 90% / 100%). Dealing CRIT Damage with this weapon grants (+6.2% / 7.44% / 8.68% / 9.92% / 11.16% / 12.5%) Multishot for 12s (up to 10 stacks). Effect is removed when switching weapons.',
    stats: {
      critChance: '25%',
      critDamage: '200%',
      atkSpeed: 1,
      triggerProbability: '15%',
      multishot: 1,
      magCapacity: 20,
      maxAmmo: 150,
      ammoConversionRate: '60%',
    },
    attributes: {
      'Projectile DMG': '47%',
    },
  },
  'sacrosanct-decree': {
    element: 'Neutral',
    skillType: 'Skill',
    passiveEffect: 'Multishot (+37.5% / 45% / 52.5% / 60% / 67.5% / 75%). When this weapon triggers a bonus effect on hit, increases Melee Weapon DMG by (35.0% / 42% / 49% / 56% / 63% / 70%) for 12.0s.',
    stats: {
      critChance: '25%',
      critDamage: '205%',
      atkSpeed: 1,
      triggerProbability: '30%',
      multishot: 1,
      magCapacity: 15,
      maxAmmo: 150,
      ammoConversionRate: '40%',
    },
    attributes: {
      'Projectile DMG': '71%',
    },
  },
  'screamshot': {
    element: 'Neutral',
    skillType: 'Skill',
    passiveEffect: 'Skill Duration (+18% / 21.6% / 25.2% / 28.8% / 32.4% / 36%).',
    stats: {
      critChance: '20%',
      critDamage: '180%',
      atkSpeed: 1,
      triggerProbability: '20%',
      multishot: 1,
      magCapacity: 6,
      maxAmmo: 60,
      ammoConversionRate: '50%',
    },
    attributes: {
      'Explosion DMG': '30%',
      'Number of Projectiles': 5,
    },
  },
  'searing-sandwhisper': {
    element: 'Neutral',
    skillType: 'Skill',
    passiveEffect: 'ATK Speed (+25% / 30% / 35% / 40% / 45% / 50%). Each enemy struck by a single arrow increases the arrow\'s damage by (9% / 10.8% / 12.6% / 14.4% / 16.2% / 18%), with a maximum increase of (45% / 54% / 63% / 72% / 81% / 90%).',
    stats: {
      critChance: '19%',
      critDamage: '200%',
      atkSpeed: 1,
      triggerProbability: '20%',
      multishot: 1,
      maxAmmo: 50,
      ammoConversionRate: '50%',
    },
    attributes: {
      'Projectile DMG': '35%',
      'Projectile DMG - Phase 2': '60.0%',
      'Projectile DMG - Phase 3': '143.0%',
      'Projectile Calibre': '0.2m',
      'Projectile Calibre - Phase 2': '1.0m',
      'Projectile Calibre - Phase 3': '1.0m',
    },
  },
  'silent-sower': {
    element: 'Neutral',
    skillType: 'Skill',
    passiveEffect: 'CRIT Chance (+50.0% / 60% / 70% / 80% / 90% / 100%). The projectiles it shoots attaches to the target and explodes after 3s. Projectiles attached to one another in the same position will stack up, increasing the damage and the range of the incoming explosion. When 1 / 2 / 3 projectiles are stacked, it deals (217.0% / 227.75% / 238.5% / 249.25% / 260%) / (383.0% / 398.4% / 413.8% / 429.2% / 444.6% / 460%) / (592.0% / 615.6% / 639.2% / 662.8% / 686.4% / 710%) of the original damage.',
    stats: {
      critChance: '16%',
      critDamage: '180%',
      atkSpeed: 1,
      triggerProbability: '15%',
      multishot: 1,
      magCapacity: 12,
      maxAmmo: 90,
      ammoConversionRate: '25%',
    },
    attributes: {
      'Explosion DMG': '100%',
      'Explosion DMG - Phase 2': '217%',
      'Explosion DMG - Phase 3': '383%',
      'Explosion DMG - Phase 4': '592%',
      'Explosion Radius': '2m',
      '2-Hit Explosion Radius': '3m',
      '3-Hit Explosion Radius': '4m',
      '4-Hit Explosion Radius': '5m',
    },
  },
  'silverwhite-edict': {
    element: 'Neutral',
    skillType: 'Skill',
    passiveEffect: 'ATK Speed (+25.0 / 30% / 35% / 40% / 45% / 50%)%. When this weapon triggers a bonus effect on hit, grants (+5.0% / 6% / 7% / 8% / 9% / 10%) ATK Speed for 12.0s (up to 10.0 stacks). Effect is removed when switching weapons.',
    stats: {
      critChance: '25%',
      critDamage: '235%',
      atkSpeed: 1,
      triggerProbability: '30%',
      multishot: 1,
      magCapacity: 200,
      maxAmmo: 500,
      ammoConversionRate: '330%',
    },
    attributes: {
      'Projectile DMG': '7.2%',
      'Firing Interval': '0.35shots/s',
      'Firing Interval - Phase 2': '0.25shots/s',
      'Firing Interval - Phase 3': '0.15shots/s',
      'Firing Interval - Phase 4': '0.05shots/s',
    },
  },
  'soulrend': {
    element: 'Neutral',
    skillType: 'Skill',
    passiveEffect: 'Skill Range (+36% / 43.2% / 50.4% / 57.6% / 64.8% / 72%).',
    stats: {
      critChance: '22%',
      critDamage: '205%',
      atkSpeed: 1,
      triggerProbability: '33%',
      multishot: 1,
      maxAmmo: 150,
      ammoConversionRate: '475%',
    },
    attributes: {
      'Projectile Damage': '6.3%',
      'Number of Projectiles': 7,
    },
  },
  'stellar-finality': {
    element: 'Neutral',
    skillType: 'Skill',
    passiveEffect: 'Explosion Range (+0.2 / 0.26 / 0.32 / 0.38 / 0.44 / 0.5). When its projectiles explode, they split into 6 additional projectiles that explode and deal damage. When defeating a target with this weapon, grants 1 stack that increased CRIT Damage by (8.8% / 10.56% / 12.32% / 14.08% / 15.84% / 17.5%) for 15s, up to 10 stacks. This effect is removed when switching to another weapon.',
    stats: {
      critChance: '20%',
      critDamage: '240%',
      atkSpeed: 1,
      triggerProbability: '18%',
      projectileExplosionRange: 0.5,
      multishot: 1,
      magCapacity: 8,
      maxAmmo: 40,
      ammoConversionRate: '25%',
    },
    attributes: {
      'Explosion DMG': '80%',
      'Explosion DMG - Phase 2': '15%',
      'Explosion Radius': '3m',
      '2-Hit Explosion Radius': '3m',
    },
  },
  'submerged-serenade': {
    element: 'Neutral',
    skillType: 'Skill',
    passiveEffect: 'CRIT Damage (+62.5% / 75% / 87.5% / 100% / 112.5% / 125%). Projectiles that hit the environment or travel a certain distance return to the user\'s position and increase the Ammo Count by 1. for each additional Ammo Count gained, the damage dealt by this weapon is increased by (4.5% / 5.4% / 6.3% / 7.2% / 8.1% / 9%), up to a maximum increase of (45% / 54% / 63% / 72% / 81% / 90%).',
    stats: {
      critChance: '22%',
      critDamage: '220%',
      atkSpeed: 1,
      triggerProbability: '25%',
      multishot: 1,
      maxAmmo: 10,
      ammoConversionRate: '10%',
    },
    attributes: {
      'Projectile Damage': '6%',
      'Firing Interval': '0.1 shots/s',
    },
  },
};
